config/routes.rb
Proj1::Application.routes.draw do

 devise_for :admins
 devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
 root :to => 'home#index'

 resources :users, :businesses, :contests, :prizes, :participations
 resources :admins, only: [:index]

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController


  def new
    @business = Business.new
  end

  def create
    @bartender = User.find(params[:business][:bartender][:id])
    params[:business].delete(:bartender)
    @business = Business.new(params[:business])
    @business.save

    @bartender.business_id = @business.id
    @bartender.bartender = true
    @bartender.save

    if @business
      redirect_to admins_path
    else
      flash[:notice] = "There was an error saving the business record"
    end
  end

  def index
    @business = Business.all
  end

  def show
    @bartenders = User.where(:business_id => params[:id], :bartender => true)
    @business = Business.find(params[:id])


  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    @bartender = User.find(params[:business][:bartender][:id])
    @bartender.business_id = @business.id
    @bartender.bartender = true
    @bartender.save

    params[:business].delete(:bartender)
    if @business.update_attributes(params[:business])
      redirect_to businesses_path
    else
      flash[:notice] = "Fucked up"
    end
  end

  def destroy
    @business = Business.find(params[:id])
    if @business.destroy
      redirect_to businesses_path
    else
      flash[:notice] = "Error destroying business record"
    end
  end

end

app/views/businesses/_form.html.erb
<%= semantic_form_for @business do |f| %>
  <%= f.inputs :name, :address1, :address2, :zip %>

 <h2> Please choose a bartender from the list below </h2>

    <%= f.inputs :for => :bartender do |bartender| %>
    <% if current_user.admin or current_user.bartender %>
      <%= bartender.input :id, :as => :select, :collection => Hash[User.all.map{|b| [b.username, b.id]}]
    %>
      <%end%>
  <%end%>
  <p></p>
  <%= f.action :submit %>
  <%= link_to :back %>
<% end %>

app/views/businesses/edit.html.erb
<div class = "Edit_Business">

    <%= render :partial => "form" %>

</div>

app/views/businesses/follow.html.erb
success

app/views/businesses/index.html.erb
<div class="Bars" </div>
<strong>Bars</strong>
<% if Business.dbEmpty %>
  <h2> No businesses on file </h2>
  <% else %>
   <p>
    <% @businesses = Business.all %>
    <% @businesses.each do |f| %>
    <ol>
      <li>Bar Name:<%= link_to f.name, business_path(f.id) %></li>
                   <%= button_to "Delete Bar", f, :method => :delete %>
    </ol>
    <%end%>
 <%end%>
</div>
<div class = "New_Bar">
  <%= link_to "Add Bar", new_business_path%>
</div>

app/views/businesses/new.html.erb
<div class = "New_Business">

    <%= render partial: "form" %>

</div>

app/views/businesses/show.html.erb
  <li>Business Name: <%= @business.name %></li>
  <li>Business Address1: <%= @business.address1%></li>
  <li>Business Address2: <%= @business.address2%></li>
  <li>Business ZIP: <%=  @business.zip %></li>
  <% if current_user.admin == false%>
    <li><% @bartenders.each do |x|  %>
        <h3><%=x.name%></h3>
           <a href="https://twitter.com/<%="#{x.username}"%>" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow <%="#{x.username}"%></a>
           <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
           <%end%>
     <%elsif current_user.admin%>
      <%= link_to "edit", edit_business_path(@business) %>
 <%end%>
 <p></p>
  Latest announcements at the bar:
  <% @bartenders.each do |x| %>
    <%x.pull_tweets.each do |timeline| %>
      <blockquote><%= timeline.text %></blockquote>
      <div class="from">&mdash; @<%= timeline.user[:screen_name] %></div>
     <% end %>
  <%end%>