config/routes.rb
Proj1::Application.routes.draw do

 devise_for :admins
 devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
 root :to => 'home#index'

 resources :users, :businesses, :contests, :prizes, :participations
 resources :admins, only: [:index]

end

app/views/admins/_menu_items.html.erb
  <div class = "admin_nav">
  <ol>
    <li><%= link_to "contests", contests_path%></li>
    <li><%= link_to "prizes", prizes_path%></li>
    <li><%= link_to "businesses", businesses_path%></li>
    <li><%= link_to "participations", participations_path%></li>
  </ol>
</div>

app/views/admins/index.html.erb
<div class = "Admin_View">
  <h1>Admin Console</h1>
  <div class = "Users">
    <h2>Users</h2>
    <% @users.each do |f| %>
    <ul>
      <li>Registration for <%= link_to f.username, edit_user_registration_path(f) %></li>
      <li>Additional info <%= link_to f.username, edit_user_path(f) %>
    </ul>
    <%end%>
  </div>

  <p></p>

  <div class="Bars">
    <h2>Bars</h2>
    <% if Business.dbEmpty %>
      <strong> No businesses on file </strong>
      <% else %>
       <p>
        <ol>
        <% @businesses.each do |f| %>
          <li>Bar Name: <%= link_to f.name, f%></li>
        <%end%>
        </ol>
     <%end%>
    <div class = "New_Bar">
      <%= link_to "Add Bar", new_business_path%>
    </div>
  </div>

  <p></p>
  <div class="Contests">
    <h2>Contests</h2>
    <% if Contest.first.nil? && Prize.first.nil? %>
      <strong> No contests on file. You must first create a prize before adding a contest. </strong>
    <% elsif Prize.first.nil? %>
      <strong> No prizes on file. You must add a prize. </strong>
    <% else %>
      <ol>
      <% @contests.each do |c| %>
         <li>Contest Name: <%= link_to c.name, c%></li>
      <%end%>
      <div class = "New_Contest">
        <%= link_to "Add Contest", new_contest_path%>
      </div>
      </ol>
    <%end%>

  </div>

  <div class="Prizes">
    <h2>Prizes</h2>
    <% if Prize.first.nil? %>
      <strong> No prizes on file </strong>
    <% else %>
      <ol>
      <% @prizes.each do |p| %>
         <li>Prize Name: <%= link_to p.name, prize_path(p) %></li>
      <%end%>
      </ol>
    <%end%>
    <div class = "New_Prize">
      <%= link_to "Add Prize", new_prize_path%>
    </div>
  </div>


</div>