config/routes.rb
Proj1::Application.routes.draw do

 devise_for :admins
 devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
 root :to => 'home#index'

 resources :users, :businesses, :contests, :prizes, :participations
 resources :admins, only: [:index]

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :name, :description, :user_id, :prizes_attributes, :prize_ids, :prize_quantity
  before_save :delete_empty_prize
  has_many :participations
  has_many :users, :through => :participations
  has_many :prizes, :dependent => :destroy

  validates_presence_of :description
  validates_presence_of :name

  accepts_nested_attributes_for :prizes

  def delete_empty_prize
    self.prizes.delete_if { |prize|
       prize.id ==nil
    }
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

  def new
    if current_user.admin
      @contest = Contest.new
      @contest.prizes.build
    else
      redirect_to '/'
    end
  end


  def create
    @contest = Contest.new(params[:contest])
    @contest.prizes.build(params[:prizes])
    if @contest.save
      redirect_to @contest
    else
      flash[:notice] = "No good muthafucka"
    end
  end

  def index
    if current_user.bartender
      @contests = current_user.contests


    else
      @contests = Contest.all
    end
  end


  def show
    @contest = Contest.find(params[:id])
  end

  def edit
    @contest = Contest.find(params[:id])

  end

  def update
    @contest = Contest.find(params[:id])
    if @contest.prizes.empty?
      @contest.prizes.create(params[:prizes])
    elsif @contest.update_attributes(params[:contest])
      redirect_to @contest
    else
      redirect_to contests_path
    end
  end

  def destroy
    @contest = Contest.find(params[:id])
    if @contest.destroy
      redirect_to contests_path
    else
      flash[:notice] = "Error"
      redirect_to :back
    end
  end

end

app/helpers/contests_helper.rb
module ContestsHelper


 end

app/views/contests/_form.html.erb
<%= form_for @contest do |contest| %>
  <%= contest.text_field :name%>
  <p>
  <%= contest.text_area :description %>
  <p>
       <% Prize.order(:name).each do |prize| %>
            <p>
           <span><%= prize.name %></span>
            <%= check_box_tag 'contest[prize_ids][]', prize.id, prize.id.in?(@contest.prizes), {class: "checkbox inline"} %>
          <% end %>
        <p>
  <%= contest.label :prize_quantity %>
  <%= contest.text_field :prize_quantity %>
<%=contest.submit %>
<%end%>

app/views/contests/edit.html.erb
<h1> Edit Contest </h1>
<%= render :partial => 'form'%>

app/views/contests/index.html.erb
<% if @contests.empty? %>
  <h2> You have no current contests </h2>
<%end%>

<% if current_user.admin %>
  <ol>
  <% @contests.each do |contest|  %>
    <li><%= link_to contest.name, edit_contest_path(contest) %></li>
    <%= button_to "delete", contest, :method => :delete %>
  <%end%>
  <%= link_to "New Contest", new_participation_path %>
 </ol>
  <ol>
<% elsif current_user.bartender? %>
  <%= link_to "New Contest", new_participation_path, :class => "btn" %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @contests.each do |contest| %>
        <tr>
          <td><%= contest.id %></td>
          <td><%= link_to contest.name, edit_contest_path(contest) %></td>
          <td>
            <%= link_to "Delete", Participation.find_by_contest_id(contest.id), :method => :delete, :class => "btn btn-danger" -%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
<%end%>

app/views/contests/new.html.erb
<h1> New Contest Setup </h1>
<%= render :partial => 'form' %>

app/views/contests/show.html.erb
<h1><%= @contest.name %></h1>
<%= @contest.description %>
<p>
<%= @contest.prize_quantity%>
<p>
<% @contest.prizes.each do |x| %>
  <% p = Prize.find(x) %>
  <%= image_tag(p.url) %>
<%end%>
<p>
<%= link_to "Edit Contest", edit_contest_path(@contest) %>